### ISSUE TITLE
Display Address as ERC-67

### ISSUE THREAD

**Issue by ligi** [manuelsc/Lunary-Ethereum-Wallet#10]
Hi, I just implemented main-net support into WALLETH and wanted to try out the interoperability of our wallets - but then I saw you use the following format in the QRCode:

iban:<plain-eth-addres-hex>

I think this is wrong. The only document I found regarding this is: https://github.com/ethereum/wiki/wiki/ICAP:-Inter-exchange-Client-Address-Protocol 
And I find no mention of the style used in Lunary.

I would propose you use ERC-67 - was also giving some arguments in my talk (http://walleth.org/2017/07/01/WALLETH-talk-video/) why I think this is a good idea.

Would also be OK with ICAP - but imho then this should be in the correct style. But then this also makes intent-filters hard and we would clash with other apps that use iban for other purposes - I would prefer ERC-67

**Comment by manuelsc** [comment]
It's on my todo list ever since we briefly talked on reddit about it. Good point about the intent-filter clash with ICAP.
So our current plan is to make ERC-67 the default encoding standard for Lunary and support ICAP scanning as well to allow cross interaction with Jaxx. I just have no eta on those yet but we'll support them in one of the next versions.
And congratulations on your main-net support, also glad to see you pushing for cross interaction support of our wallets.

**Comment by manuelsc** [comment]
Support added in 46859f623fe07291ef9b5f637eb63b2e2e5b66bd and 08c309f98c55a4ec4b1ca9fb5918f4a83b5ca55f 
ERC-67 and ICAP scanning is fully functional. QR creation is disabled by default right now so it won't interfere with users running older versions but users can already opt in by enabling it in Lunarys settings. We're switching to default ERC-67 QR encoding as soon as  a majority of users running 1.29+.

**Comment by manuelsc** [comment]
Is now the default behavior since 734f4f628c37621aa7e152ba7f36bb6021f4c880 (1.31)

**Comment by ligi** [comment]
Are you at DevCon3 by any chance? Would love to see you to be part of this: https://github.com/ethereum/EIPs/pull/681#issuecomment-340258656

**Comment by manuelsc** [comment]
Unfortunately not, but I'll keep an eye on the proposal and the outcome after your sit down at devcon.
