### ISSUE TITLE
Wrong German translation

### ISSUE THREAD

**Issue by amilopowers** [manuelsc/Lunary-Ethereum-Wallet#22]
The buttons to send/receive are named confusing.
![screenshot_20171203-172650](https://user-images.githubusercontent.com/9914682/33527365-a30bbbf2-d84f-11e7-88e7-7301523897fa.png)

Button to send ETH should be called: "Ether senden an", the button to receive/request: "Ether empfangen von".

**Comment by vandenbrande** [comment]
Hi, Thank you for contacting us.  This is a confirmation that your e-mail has been received. We will reply to your e-mail within 24-48 hours. Have a nice day!  Best regards,  ArduinoSensors.nl

**Comment by amilopowers** [comment]
And "Account Kontostand" makes no sense since the word "Kontostand" includes account. So just "Kontostand" is perfect.

**Comment by manuelsc** [comment]
Fixed "Kontostand" in 472236c1ba32c540b05276b6a6e663aa42127734 build 1.35
"Sende Ether von/zu" is correct since it determines whether you want to send ether from this address to someone else (only available if this is your own wallet) or "zu" if you want to transfer ether to that wallet ("normal" option).

**Comment by amilopowers** [comment]
I switched to english and I agree that they mean the same in both languages. However they are really confusing.
