### ISSUE TITLE
Crash when changing price history view

### ISSUE THREAD

**Issue by 741N** [manuelsc/Lunary-Ethereum-Wallet#24]
When I change from last 24 hrs, to last 30 days, to last year, the app will crash, each time. No exceptions. Reopening the app, and going to the price history view will open it to whatever I was trying to switch to (e.g. if it crashed when swiping from 24 hrs to year it'll open after the crash in year-view). 

I'm running version 1.34 installed from f-droid (although f-droid is now telling me that's an incompatible version, "different signature to installed version", even though I'm 100% sure I installed it in f-droid?); Android 7.1.2

**Comment by manuelsc** [comment]
This bug was fixed in 1.35. F-Droid hasn't compiled and signed 1.35 yet. 
About the signature missmatch, F-Droid compiles and signes Lunary from this repo while the apk provided here is signed with the same key as the google play store build. Hence the missmatch. You can't switch to a build with a different signature without uninstalling it first. But don't try to uninstall and install Lunary 1.35 without a proper backup of your wallet!
