### ISSUE TITLE
Ability to view unencrypted private key

### ISSUE THREAD

**Issue by bin4ryio** [manuelsc/Lunary-Ethereum-Wallet#26]
Firstly, thanks for the great wallet app. It's been a great user experience. However, I've created a 2nd wallet and using a password generator to generate password with symbol, now I cannot send fund because it says password invalid, I'm guessing if there's something wrong with symbol encoding.

Is there a way to view my own private key unencrypted like MyEtherWallet?

Thank you.

**Comment by manuelsc** [comment]
Please don't create multiple issues on multiple platforms. I already answered your question on reddit https://www.reddit.com/r/lunary/comments/7m3a5y/ability_to_export_private_key_unencrypted/?st=jboyrrfd&sh=4a6f2a28
If you give me an example of the character you think causes this issue I can take a further look. You can also contact me at support@rehanced.com in case you don't want to disclose a character of your password on github.

**Comment by bin4ryio** [comment]
Sorry, I thought /r/lunary is more of a community and feature request should be in GitHub issue.

**Comment by manuelsc** [comment]
I'm closing this issue since the feature requested here is basically covered by the "export wallet" feature. Viewing the private key of an encrypted wallet is simply not possible (besides the fact that this would drastically compromise security) since your password is needed to decrypt your private key.
About your personal wallet issue: Any luck recovering your password? As I suggested on reddit, may try different variations of your password in case you made a mistake while you wrote it down or entered it in Lunary.

**Comment by manuelsc** [comment]
There was an issue with the F-Droid build which reminded me a bit about this issue. Hopefully this helps you: https://www.reddit.com/r/lunary/comments/7okpse/psa_fdroid_export_issue_private_key_recovery/?st=jc3qe3o7&sh=306b0977
