### ISSUE TITLE
Wallets created pre-1.25 ask for non-existent password

### ISSUE THREAD

**Issue by danielquinn** [manuelsc/Lunary-Ethereum-Wallet#31]
I installed Lunary a long time ago, back when creating a wallet didn't ask me for a password, but now that I've upgraded, it's asking me for a password that I never gave it.  What's the recommended way to fix this?  Is there a default password that would have been used?

**Comment by manuelsc** [comment]
Which version are you running? Lunary has always been asking for a password during wallet setup - it's mandatory since the very first release back in june 2017.

**Comment by danielquinn** [comment]
Well I installed it a long time ago, but didn't put any eth in the wallet that I created at the time.  Much (much) later, I put some cash into it and then found that I couldn't get anything out without a password :-(

I'm pretty sure I installed it from f-droid sometime before passwords appear to have been introduced in 1.25, but am now running 1.37, as it's been upgrading regularly.

If passwords have always been a thing, is it possible that the 9-character rule wasn't always in there?  I just have no passwords in my bank of options that are that long, so I'm struggling to figure out how to get my eth out of there now.

**Comment by manuelsc** [comment]
In case you installed Lunary on an arm64 chip device please checkout this issue: https://www.reddit.com/r/lunary/comments/7okpse/psa_fdroid_export_issue_private_key_recovery/?st=jduhelsx&sh=e0f0d0fb

F-Droid's build server causes some weird problems with the native libscrypt library. You may want to checkout the Lunary Recovery version and try your different passwords there - hopefully it will help you unlock your wallet.
Additionally try exporting your wallet and see if it unlocks in MEW or Mist.

I'm not aware of any other password related issue than the big one mentioned above. 9 char limit and passwords in general are enforced since version 1.
